- block:
  - name: locales | generate tty console keyboard and font
    template:
      src:   vconsole.conf
      dest:  "{{ vconsole_path }}"
      owner: root
      group: root
      mode:  0644

  when: keymap | length
  tags: keymap
