- block:
  - name: locales | generate locales
    locale_gen:
      name:  "{{ item       | default(item.name) }}"
      state: "{{ item.state | default('present') }}"
    loop: "{{ locales }}"

  - name: locales | enable system locales
    template:
      src:   locale.conf
      dest:  "{{ locale_path }}"
      owner: root
      group: root
      mode:  0644

  when: locales | length
  tags: locales
