- block:
  - name: locales | generate locales
    locale_gen:
      name:  "{{ item.name }}"
      state: "{{ item.state | default('present') }}"
    loop: "{{ locales }}"

  - name: locales | enable system locales
    template:
      src:   locale.conf
      dest:  "{{ locale_path }}"
      owner: root
      group: root
      mode:  0644

  # - name: "[copy] set default language to local.gen"
  #   copy:
  #     dest: /etc/locale.gen
  #     content: |
  #       en_US.UTF-8 UTF-8
  #       fr_FR.UTF-8 UTF-8
  #       fr_FR ISO-8859-1
  #       fr_FR@euro ISO-8859-15
  #       en_US ISO-8859-1
  #       # ja_JP.UTF-8                 # japanese, KO: ne fonctionne pas sans certains package préinstallé
  #       # zh_CN.UTF-8 UTF-8           # chinese, //
  #   register: _local_gen

  # - name: "[shel] generate local language"
  #   shell: locale-gen
  #   when:  _local_gen.changed

  # - name: "[copy] define default language to {{ _local_dest }}"
  #   copy:
  #     dest: "/etc/{{ _local_dest }}"
  #     content: |
  #       LANG="fr_FR.UTF-8"
  #       LANGUAGE="fr_FR:en_US"
  #       # LANG="en_US.UTF-8"
  #       # LANGUAGE="en_US:fr_FR"
  #       # LC_COLLATE="C.UTF-8"

  tags: locales
