- block:
  # can't run in chroot: fatal: [chroot]: FAILED! => {"changed": false, "msg": "Error message:\ntried to configure name using a file \"/etc/sysconfig/clock\", but could not write to it"}
  - name: timezone | set timezone to {{ timezone }}
    timezone:
      name: "{{ timezone }}"
    when: not chroot

  - name: timezone | file > link zoneinfo/{{ timezone }} to /etc/localtime
    file:
      src:   "/usr/share/zoneinfo/{{ timezone }}"
      dest:  /etc/localtime
      state: link
      force: yes
    when: sysinit == "systemd"
    when: chroot

  when: timezone | length
  tags: timezone
