- block:
  # KO in chroot: file "/etc/sysconfig/clock" doesn't exist in Arch ?
  - name: timezone | set timezone to {{ timezone }}
    timezone:
      name: "{{ timezone }}"
    when: not chroot

  # OK in chroot
  - name: timezone | file > link zoneinfo/{{ timezone }} to /etc/localtime
    file:
      src:   "/usr/share/zoneinfo/{{ timezone }}"
      dest:  /etc/localtime
      state: link
      force: yes
    when:
      - chroot

  when: timezone | length
  tags: timezone
