- block:
  - name: timezone | set timezone to {{ timezone }}
    timezone:
      name: "{{ timezone }}"

  ## old: TO REMOVE
  # - name: "[systemd] [file] link zoneinfo/{{ timezone }} to /etc/localtime"
  #   file:
  #     src:   "/usr/share/zoneinfo/{{ timezone }}"
  #     dest:  /etc/localtime
  #     state: link
  #     force: yes
  #   when: sysinit == "systemd"

  tags: timezone
